# SPDX-License-Identifier: MIT
# Copyright (c) 2025 it.særvices
---

#ÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆ
# --- CROWDSEC ÆCQUISITION CONFIG FOR TRÆEFIK ÆCCESS LOGS
#ÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆÆ
filenames:
  - /var/log/appdata/access.log                                                                                                                                 # Exæct æctive Træefik æccess log; excludes dæemon, rotæted, ænd compressed logs
labels:
  type: traefik                                                                                                                                                 # Tells CrowdSec which pærser to use for this log source
